// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/20/2025, 10:24:14 AM
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["D:/laragon/www/nuxt/demo/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/laragon/www/nuxt/demo/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/laragon/www/nuxt/demo/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/laragon/www/nuxt/demo/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/laragon/www/nuxt/demo/plugins/**/*.{js,ts,mjs}","D:/laragon/www/nuxt/demo/composables/**/*.{js,ts,mjs}","D:/laragon/www/nuxt/demo/utils/**/*.{js,ts,mjs}","D:/laragon/www/nuxt/demo/pages/cart.vue","D:/laragon/www/nuxt/demo/pages/about.vue","D:/laragon/www/nuxt/demo/pages/index.vue","D:/laragon/www/nuxt/demo/pages/login.vue","D:/laragon/www/nuxt/demo/pages/contact.vue","D:/laragon/www/nuxt/demo/pages/register.vue","D:/laragon/www/nuxt/demo/pages/products/[id].vue","D:/laragon/www/nuxt/demo/pages/products/index.vue","D:/laragon/www/nuxt/demo/pages/products/[id] copy.vue","D:/laragon/www/nuxt/demo/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/laragon/www/nuxt/demo/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/laragon/www/nuxt/demo/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;